steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/mlflow-service:latest", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/mlflow-service:latest"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [
        "run",
        "deploy",
        "mlflow-service",
        "--image=gcr.io/$PROJECT_ID/mlflow-service:latest",
        "--region=northamerica-northeast2",
        "--allow-unauthenticated", # authentication handled on the backend
        "--memory=4Gi",
        "--service-account=${_SERVICE_ACCOUNT}",
        "--add-cloudsql-instances=${_SQL_INSTANCE}",
        "--set-env-vars",
        "GCP_PROJECT=$PROJECT_ID",
      ]

  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   entrypoint: gcloud
  #   args: [
  #       "update",
  #       "mlflow-service",
  #       "--add-cloudsql-instances=",
  #       "--update-env-vars=INSTANCE_CONNECTION_NAME="
  #       "--update-secrets=DB_USER="
  #       "--update-secrets=DB_PASS="
  #       "--update-secrets=DB_NAME="

  #     ]

# Optional images configuration to specify global image substitution variables
images:
  - "gcr.io/$PROJECT_ID/mlflow-service:latest"

options:
  logging: CLOUD_LOGGING_ONLY
  